version: "3.7"

services:

  allergy-tp:
    image: sebastianbran/allergy-processor:latest
    container_name: allergy-tp-default
    depends_on:
      - validator
    entrypoint: python3 -u main.py -vv -C tcp://validator:4004

  family-history-tp:
    image: sebastianbran/family-history-processor:latest
    container_name: family-history-tp-default
    depends_on:
      - validator
    entrypoint: python3 -u main.py -vv -C tcp://validator:4004

  consent-tp:
    image: sebastianbran/consent-processor:latest
    container_name: consent-tp-default
    depends_on:
      - validator
    entrypoint: python3 -u main.py -vv -C tcp://validator:4004

  patient-tp:
    image: sebastianbran/patient-processor:latest
    container_name: patient-tp-default
    depends_on:
      - validator
    entrypoint: python3 -u main.py -vv -C tcp://validator:4004

  practitioner-tp:
    image: sebastianbran/practitioner-processor:latest
    container_name: practitioner-tp-default
    depends_on:
      - validator
    entrypoint: python3 -u main.py -vv -C tcp://validator:4004

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: sawtooth-settings-tp-default
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  intkey-tp-python:
    image: hyperledger/sawtooth-intkey-tp-python:chime
    container_name: sawtooth-intkey-tp-python-default
    depends_on:
      - validator
    entrypoint: intkey-tp-python -vv -C tcp://validator:4004

  validator:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-default
    expose:
      - 4004
    ports:
      - "4004:4004"
    # start the validator with an empty genesis batch
    entrypoint:
      - "bash"
      - "-c"
      - |
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawset proposal create \
          -k /root/.sawtooth/keys/my_key.priv \
          sawtooth.consensus.algorithm.name=Devmode \
          sawtooth.consensus.algorithm.version=0.1 \
          -o config.batch && \
        sawadm genesis config-genesis.batch config.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050


  devmode-engine:
    image: hyperledger/sawtooth-devmode-engine-rust:chime
    container_name: sawtooth-devmode-engine-rust-default
    depends_on:
      - validator
    entrypoint: devmode-engine-rust -C tcp://validator:5050

  rest-api:
    image: hyperledger/sawtooth-rest-api:chime
    container_name: sawtooth-rest-api-default
    ports:
      - "80:80"
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -C tcp://validator:4004 --bind rest-api:80

  shell:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default
    depends_on:
      - rest-api
    entrypoint:
      - "bash"
      - "-c"
      - |
        sawtooth keygen && \
        tail -f /dev/null
